# Generated by Django 4.2 on 2025-01-17 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"verbose_name": "Task", "verbose_name_plural": "Tasks"},
        ),
        migrations.AlterModelOptions(
            name="tasktype",
            options={"verbose_name": "Task Type", "verbose_name_plural": "Task Types"}, # NOQA E501
        ),
    ]
