# Generated by Django 4.2 on 2025-01-17 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("worker", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="position",
            options={"verbose_name": "Position", "verbose_name_plural": "Positions"}, # NOQA E501
        ),
        migrations.AlterModelOptions(
            name="worker",
            options={"verbose_name": "Worker", "verbose_name_plural": "Workers"}, # NOQA E501
        ),
    ]
