# Generated by Django 4.2 on 2025-01-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worker", "0002_alter_position_options_alter_worker_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="worker",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="worker",
            name="status",
            field=models.SmallIntegerField(
                choices=[(1, "Active"), (2, "On Leave"), (3, "Terminated")], default=1
            ),
        ),
    ]
