# Generated by Django 4.2 on 2025-01-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worker", "0003_worker_country_worker_phone_number_worker_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="worker",
            options={
                "ordering": ["-id"],
                "verbose_name": "Worker",
                "verbose_name_plural": "Workers",
            },
        ),
        migrations.AlterField(
            model_name="worker",
            name="status",
            field=models.SmallIntegerField(
                blank=True,
                choices=[(1, "Active"), (2, "On Leave"), (3, "Terminated")],
                default=1,
            ),
        ),
    ]
