# Generated by Django 4.2 on 2025-01-17 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"verbose_name": "Project", "verbose_name_plural": "Projects"},  # NOQA E501
        ),
        migrations.AlterModelOptions(
            name="team",
            options={"verbose_name": "Team", "verbose_name_plural": "Teams"},
        ),
        migrations.AlterField(
            model_name="team",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                to="project.project",
            ),
        ),
    ]
