# Generated by Django 4.2 on 2025-01-17 14:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0003_alter_project_options_alter_team_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="members",
            field=models.ManyToManyField(
                related_name="team", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
